export const DEG_TO_RAD = Math.PI / 180;
export const RAD_TO_DEG = 180 / Math.PI;

export const GRATICULE_POINT_STEP_DEG = 10;
export const DEFAULT_GRATICULE_MERIDIAN_STEP_DEG = 30;
export const DEFAULT_GRATICULE_PARALLEL_STEP_DEG = 30;
export const GRATICULE_RADIUS_OFFSET = 1.004;

export const FOOTPRINT_LINE_RADIUS_OFFSET = 1.005;
export const FOOTPRINT_LINE_WIDTH_PX = 1.25;
export const MANUAL_TARGET_RADIUS_OFFSET = 1.02;
