import { defineSlotRecipe } from "@chakra-ui/react";

export const sourcesRecipe = defineSlotRecipe({
	className: "target-hub-sheet-sources",
	slots: [
		"panelBody",
		"panelContent",
		"title",
		"section",
		"sectionHeader",
		"sectionTitle",
		"sectionCount",
		"sectionList",
		"sectionEmpty",
		"emptyState",
		"emptyTitle",
		"emptyDescription",
	],
	base: {
		panelBody: {
			minH: 0,
			flex: "1",
			overflow: "hidden",
			display: "flex",
			flexDirection: "column",
		},
		panelContent: {
			minH: 0,
			flex: "1",
			overflowY: "auto",
			display: "flex",
			flexDirection: "column",
			gap: 2,
			pr: 1,
		},
		title: {
			fontSize: "sm",
			fontWeight: "semibold",
			color: "white",
		},
		section: {
			display: "flex",
			flexDirection: "column",
			gap: 2,
		},
		sectionHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 2,
		},
		sectionTitle: {
			minW: 0,
			fontSize: "xs",
			fontWeight: "semibold",
			color: "whiteAlpha.780",
			textTransform: "uppercase",
			letterSpacing: "0.08em",
		},
		sectionCount: {
			minW: "24px",
			h: "20px",
			px: 2,
			borderRadius: "full",
			borderWidth: "1px",
			borderColor: "whiteAlpha.140",
			bg: "rgba(255, 255, 255, 0.035)",
			color: "whiteAlpha.700",
			fontSize: "xs",
			fontWeight: "semibold",
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			lineHeight: 1,
		},
		sectionList: {
			display: "flex",
			flexDirection: "column",
			gap: 2,
		},
		sectionEmpty: {
			px: 3,
			py: 2,
			borderRadius: "lg",
			borderWidth: "1px",
			borderStyle: "dashed",
			borderColor: "whiteAlpha.120",
			bg: "rgba(255, 255, 255, 0.018)",
			color: "whiteAlpha.560",
			fontSize: "xs",
		},
		emptyState: {
			p: 4,
			borderRadius: "xl",
			borderWidth: "1px",
			borderStyle: "dashed",
			borderColor: "whiteAlpha.140",
			bg: "rgba(255, 255, 255, 0.02)",
		},
		emptyTitle: {
			fontSize: "sm",
			fontWeight: "semibold",
			color: "white",
		},
		emptyDescription: {
			fontSize: "xs",
			color: "whiteAlpha.720",
			mt: 1,
		},
	},
});
