import { defineSlotRecipe } from "@chakra-ui/react";
import {
	SHEET_BOTTOM_OFFSET,
	SHEET_LEFT_OFFSET,
	SHEET_TOP_OFFSET,
	SHEET_WIDTH,
	TARGET_HUB_Z_INDEX,
} from "../../shared/constants";

export const sheetRecipe = defineSlotRecipe({
	className: "target-hub-sheet",
	slots: [
		"root",
		"shell",
		"header",
		"headerActions",
		"titleEyebrow",
		"title",
		"currentCard",
		"editorHeader",
		"editorHeaderActions",
		"editorRow",
		"inlineField",
		"inlineFieldLabel",
		"editableField",
		"readonlyField",
		"editorActions",
		"helperText",
		"chipGroup",
		"chip",
		"panelBody",
		"panelContent",
		"sourceCard",
		"sourceIndicator",
		"sourceControls",
		"emptyState",
		"drawer",
		"drawerHeader",
		"drawerBody",
	],
	base: {
		root: {
			position: "fixed",
			left: `${SHEET_LEFT_OFFSET}px`,
			top: `${SHEET_TOP_OFFSET}px`,
			bottom: `${SHEET_BOTTOM_OFFSET}px`,
			w: `min(${SHEET_WIDTH}px, calc(100vw - 32px))`,
			zIndex: TARGET_HUB_Z_INDEX,
		},
		shell: {
			h: "100%",
			display: "flex",
			flexDirection: "column",
			p: 3,
			gap: 3,
			borderRadius: "2xl",
			borderWidth: "1px",
			borderColor: "border.subtle",
			bg: "rgba(11, 19, 32, 0.82)",
			backdropFilter: "blur(18px)",
			boxShadow: "0 24px 60px rgba(2, 8, 23, 0.42)",
			overflow: "hidden",
		},
		header: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 3,
			pb: 3,
			borderBottomWidth: "1px",
			borderColor: "whiteAlpha.100",
		},
		headerActions: {
			display: "flex",
			alignItems: "center",
			gap: 2,
		},
		titleEyebrow: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.22em",
			textTransform: "uppercase",
			color: "cyan.200",
		},
		title: {
			fontSize: "lg",
			fontWeight: "semibold",
			color: "white",
			letterSpacing: "-0.02em",
		},
		currentCard: {
			display: "flex",
			flexDirection: "column",
			gap: 2.5,
			p: 3,
			borderRadius: "xl",
			borderWidth: "1px",
			borderColor: "whiteAlpha.140",
			bg: "rgba(255, 255, 255, 0.04)",
			flexShrink: 0,
		},
		editorHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 2,
			minH: "28px",
		},
		editorHeaderActions: {
			display: "flex",
			alignItems: "center",
			gap: 2,
			minH: "28px",
			justifyContent: "flex-end",
		},
		editorRow: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 3,
			alignItems: "center",
			w: "full",
		},
		inlineField: {
			display: "grid",
			gridTemplateColumns: "72px minmax(0, 1fr)",
			alignItems: "center",
			gap: 2,
			minW: 0,
			w: "full",
		},
		inlineFieldLabel: {
			fontSize: "11px",
			fontWeight: "bold",
			letterSpacing: "0.1em",
			textTransform: "none",
			color: "whiteAlpha.680",
			whiteSpace: "nowrap",
		},
		editableField: {
			h: "32px",
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "whiteAlpha.240",
			bg: "rgba(255, 255, 255, 0.06)",
			color: "white",
			fontSize: "sm",
			px: 3,
			w: "full",
			transition:
				"border-color 120ms ease, background 120ms ease, box-shadow 120ms ease",
			_hover: {
				borderColor: "whiteAlpha.320",
				bg: "rgba(255, 255, 255, 0.08)",
			},
			_focusWithin: {
				borderColor: "cyan.300",
				boxShadow: "0 0 0 1px rgba(34, 211, 238, 0.22)",
			},
		},
		readonlyField: {
			minH: "32px",
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "whiteAlpha.100",
			bg: "rgba(255, 255, 255, 0.025)",
			color: "whiteAlpha.860",
			fontSize: "sm",
			px: 3,
			w: "full",
			display: "flex",
			alignItems: "center",
			fontVariantNumeric: "tabular-nums",
		},
		editorActions: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 2,
		},
		helperText: {
			fontSize: "xs",
			color: "whiteAlpha.700",
			lineHeight: 1.5,
		},
		chipGroup: {
			display: "flex",
			alignItems: "center",
			gap: 1.5,
		},
		chip: {
			minW: "28px",
			h: "28px",
			borderRadius: "full",
			borderWidth: "1px",
			borderColor: "whiteAlpha.200",
			bg: "transparent",
			color: "whiteAlpha.820",
			fontSize: "xs",
			fontWeight: "bold",
			letterSpacing: "0.08em",
			transition:
				"background 120ms ease, border-color 120ms ease, color 120ms ease",
			_hover: {
				bg: "whiteAlpha.120",
			},
			_disabled: {
				opacity: 0.42,
			},
		},
		panelBody: {
			minH: 0,
			flex: "1",
			overflow: "hidden",
			display: "flex",
			flexDirection: "column",
		},
		panelContent: {
			minH: 0,
			flex: "1",
			overflowY: "auto",
			display: "flex",
			flexDirection: "column",
			gap: 2,
			pr: 1,
		},
		sourceCard: {
			display: "flex",
			alignItems: "flex-start",
			gap: 3,
			w: "full",
			p: 3,
			borderRadius: "xl",
			borderWidth: "1px",
			borderColor: "whiteAlpha.120",
			bg: "rgba(255, 255, 255, 0.03)",
			textAlign: "left",
			transition:
				"transform 120ms ease, background 120ms ease, border-color 120ms ease",
			_hover: {
				transform: "translateY(-1px)",
				bg: "rgba(255, 255, 255, 0.06)",
				borderColor: "whiteAlpha.220",
			},
		},
		sourceIndicator: {
			w: "10px",
			h: "54px",
			borderRadius: "999px",
			flexShrink: 0,
			mt: 0.5,
		},
		sourceControls: {
			display: "flex",
			alignItems: "center",
			gap: 1.5,
			flexShrink: 0,
			ml: "auto",
		},
		emptyState: {
			p: 4,
			borderRadius: "xl",
			borderWidth: "1px",
			borderStyle: "dashed",
			borderColor: "whiteAlpha.140",
			bg: "rgba(255, 255, 255, 0.02)",
		},
		drawer: {
			position: "fixed",
			top: `${SHEET_TOP_OFFSET}px`,
			bottom: `${SHEET_BOTTOM_OFFSET}px`,
			w: "min(320px, calc(100vw - 48px))",
			borderRadius: "2xl",
			borderWidth: "1px",
			borderColor: "border.subtle",
			bg: "rgba(9, 15, 28, 0.9)",
			backdropFilter: "blur(18px)",
			boxShadow: "0 18px 48px rgba(2, 8, 23, 0.35)",
			overflow: "hidden",
			display: "flex",
			flexDirection: "column",
			zIndex: TARGET_HUB_Z_INDEX + 1,
		},
		drawerHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 3,
			p: 4,
			borderBottomWidth: "1px",
			borderColor: "whiteAlpha.100",
		},
		drawerBody: {
			flex: "1",
			p: 4,
			color: "whiteAlpha.760",
		},
	},
});
