import { defineSlotRecipe } from "@chakra-ui/react";

export const priorDrawerRecipe = defineSlotRecipe({
	className: "spectrum-workspace-line-fit-prior-drawer",
	slots: [
		"backdrop",
		"content",
		"header",
		"titleRow",
		"titleStack",
		"title",
		"subtitle",
		"closeButton",
		"body",
		"layout",
		"selectionArea",
		"selectionGrid",
		"selectionColumn",
		"selectionHeader",
		"selectionTitle",
		"selectionContent",
		"selectionRow",
		"selectionText",
		"selectionName",
		"selectionValue",
		"priorBadge",
		"selectionEmpty",
		"editorPane",
		"editorHeader",
		"editorTitle",
		"editorSubtitle",
		"editorEmpty",
		"tabsRoot",
		"tabsList",
		"tabsTrigger",
		"tabsPanel",
		"fieldGrid",
		"field",
		"fieldLabel",
		"numberInput",
		"unitText",
		"modeGroup",
		"referenceGrid",
		"referenceColumn",
		"referenceContent",
		"previewRow",
		"previewText",
		"errorText",
		"footer",
	],
	base: {
		backdrop: {
			bg: "blackAlpha.400",
		},
		content: {
			display: "flex",
			flexDirection: "column",
			h: "100%",
			bg: "bg",
		},
		header: {
			flexShrink: 0,
			borderBottomWidth: "1px",
			borderColor: "border.muted",
			px: 4,
			py: 3,
		},
		titleRow: {
			justifyContent: "space-between",
			alignItems: "flex-start",
			gap: 3,
		},
		titleStack: {
			gap: 0,
			minW: 0,
		},
		title: {
			fontSize: "sm",
			fontWeight: "semibold",
			lineClamp: 1,
		},
		subtitle: {
			fontSize: "xs",
			color: "fg.muted",
			lineClamp: 1,
		},
		closeButton: {
			flex: "0 0 auto",
		},
		body: {
			flex: 1,
			minH: 0,
			p: 0,
		},
		layout: {
			h: "full",
			minH: 0,
			gap: 0,
		},
		selectionArea: {
			flex: "0 0 14rem",
			minH: 0,
			borderBottomWidth: "1px",
			borderColor: "border.muted",
			p: 3,
		},
		selectionGrid: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
			gap: 3,
			h: "full",
			minH: 0,
		},
		selectionColumn: {
			h: "full",
			minH: 0,
			overflow: "hidden",
			borderWidth: "1px",
			borderColor: "border.muted",
			borderRadius: "md",
			bg: "bg.subtle",
		},
		selectionHeader: {
			flexShrink: 0,
			px: 2,
			py: 1.5,
			bg: "bg.muted",
			borderBottomWidth: "1px",
			borderColor: "border.muted",
		},
		selectionTitle: {
			fontSize: "2xs",
			fontWeight: "semibold",
			color: "fg.muted",
			letterSpacing: "0",
			textTransform: "uppercase",
		},
		selectionContent: {
			flex: 1,
			minH: 0,
			gap: 1,
			overflowY: "auto",
			p: 1,
		},
		selectionRow: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr) auto",
			alignItems: "center",
			gap: 2,
			w: "full",
			px: 2,
			py: 1.5,
			borderWidth: "1px",
			borderColor: "transparent",
			borderRadius: "sm",
			bg: "transparent",
			textAlign: "left",
			cursor: "pointer",
			transition: "background 0.15s ease, border-color 0.15s ease",
			_hover: {
				bg: "bg.emphasized",
				borderColor: "border.muted",
			},
			_focusVisible: {
				outline: "2px solid",
				outlineColor: "cyan.500",
				outlineOffset: "1px",
			},
		},
		selectionText: {
			gap: 0,
			minW: 0,
		},
		selectionName: {
			fontSize: "xs",
			fontWeight: "medium",
			color: "fg",
			lineClamp: 1,
		},
		selectionValue: {
			fontSize: "2xs",
			color: "fg.muted",
			lineClamp: 1,
		},
		priorBadge: {
			flex: "0 0 auto",
			fontSize: "2xs",
		},
		selectionEmpty: {
			h: "full",
			alignItems: "center",
			justifyContent: "center",
			px: 3,
			textAlign: "center",
			color: "fg.muted",
			fontSize: "xs",
		},
		editorPane: {
			flex: 1,
			minH: 0,
			overflowY: "auto",
			p: 4,
		},
		editorHeader: {
			gap: 0,
			mb: 4,
		},
		editorTitle: {
			fontSize: "sm",
			fontWeight: "semibold",
			lineClamp: 1,
		},
		editorSubtitle: {
			fontSize: "xs",
			color: "fg.muted",
			lineClamp: 1,
		},
		editorEmpty: {
			h: "full",
			alignItems: "center",
			justifyContent: "center",
			px: 4,
			textAlign: "center",
			color: "fg.muted",
			fontSize: "sm",
		},
		tabsRoot: {
			w: "full",
		},
		tabsList: {
			display: "grid",
			gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
			w: "full",
		},
		tabsTrigger: {
			minW: 0,
			px: 1,
			fontSize: "xs",
		},
		tabsPanel: {
			mt: 4,
			p: 4,
			minH: "12rem",
			borderWidth: "1px",
			borderColor: "border.muted",
			borderRadius: "md",
			bg: "bg.subtle",
		},
		fieldGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 3,
		},
		field: {
			gap: 1,
			minW: 0,
		},
		fieldLabel: {
			fontSize: "2xs",
			fontWeight: "semibold",
			color: "fg.muted",
		},
		numberInput: {
			w: "full",
		},
		unitText: {
			fontSize: "2xs",
			color: "fg.subtle",
			minW: "2rem",
		},
		modeGroup: {
			w: "5.5rem",
		},
		referenceGrid: {
			display: "grid",
			gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
			gap: 3,
			minH: "7.5rem",
		},
		referenceColumn: {
			minH: 0,
			overflow: "hidden",
			borderWidth: "1px",
			borderColor: "border.muted",
			borderRadius: "md",
			bg: "bg",
		},
		referenceContent: {
			gap: 1,
			maxH: "6rem",
			overflowY: "auto",
			p: 1,
		},
		previewRow: {
			alignItems: "center",
			justifyContent: "space-between",
			gap: 2,
			px: 3,
			py: 2,
			borderWidth: "1px",
			borderColor: "border.muted",
			borderRadius: "md",
			bg: "bg.muted",
		},
		previewText: {
			fontSize: "xs",
			color: "fg.muted",
			lineClamp: 2,
		},
		errorText: {
			fontSize: "xs",
			color: "red.fg",
			mt: 3,
		},
		footer: {
			flexShrink: 0,
			borderTopWidth: "1px",
			borderColor: "border.muted",
			px: 4,
			py: 3,
			justifyContent: "flex-start",
		},
	},
	variants: {
		selected: {
			true: {
				selectionRow: {
					bg: "cyan.subtle",
					borderColor: "cyan.400",
					_hover: {
						bg: "cyan.subtle",
						borderColor: "cyan.400",
					},
				},
				selectionName: {
					color: "cyan.fg",
				},
			},
		},
		hasPrior: {
			true: {
				priorBadge: {
					colorPalette: "cyan",
				},
			},
			false: {
				priorBadge: {
					colorPalette: "gray",
				},
			},
		},
	},
	defaultVariants: {
		selected: false,
		hasPrior: false,
	},
});
