import { defineSlotRecipe } from "@chakra-ui/react";

export const workspacePanelRecipe = defineSlotRecipe({
	className: "image-inspector-workspace-panel",
	slots: [
		"root",
		"header",
		"titleGroup",
		"eyebrow",
		"title",
		"closeButton",
		"body",
		"rail",
		"railButton",
		"content",
	],
	base: {
		root: {
			pointerEvents: "auto",
			w: "400px",
			h: "min(640px, 60vh)",
			maxH: "min(640px, 60vh)",
			minH: "420px",
			display: "flex",
			flexDirection: "column",
			overflow: "hidden",
			borderRadius: "lg",
			borderWidth: "1px",
			borderColor: "whiteAlpha.180",
			bg: "rgba(8, 13, 20, 0.78)",
			backdropFilter: "blur(26px) saturate(170%)",
			boxShadow:
				"0 24px 56px rgba(0, 0, 0, 0.42), inset 0 1px 0 rgba(255, 255, 255, 0.08)",
		},
		header: {
			flex: "0 0 auto",
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 3,
			px: 4,
			py: 3,
			borderBottomWidth: "1px",
			borderBottomColor: "whiteAlpha.120",
		},
		titleGroup: {
			display: "flex",
			flexDirection: "column",
			gap: 0,
			minW: 0,
		},
		eyebrow: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.12em",
			textTransform: "uppercase",
			color: "whiteAlpha.640",
		},
		title: {
			fontSize: "sm",
			fontWeight: "semibold",
			color: "white",
			lineHeight: 1.2,
		},
		closeButton: {
			flex: "0 0 auto",
			w: 8,
			h: 8,
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "whiteAlpha.140",
			bg: "whiteAlpha.060",
			color: "whiteAlpha.840",
			transition: "background 0.16s ease, color 0.16s ease",
			_hover: {
				bg: "whiteAlpha.140",
				color: "white",
			},
			_focusVisible: {
				outline: "2px solid",
				outlineColor: "cyan.300",
				outlineOffset: "2px",
			},
		},
		body: {
			flex: "1 1 auto",
			minH: 0,
			display: "grid",
			gridTemplateColumns: "52px minmax(0, 1fr)",
		},
		rail: {
			minH: 0,
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			gap: 1.5,
			p: 1.5,
			borderRightWidth: "1px",
			borderRightColor: "whiteAlpha.120",
			bg: "blackAlpha.240",
		},
		railButton: {
			w: 9,
			h: 9,
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "transparent",
			color: "whiteAlpha.640",
			transition:
				"background 0.16s ease, border-color 0.16s ease, color 0.16s ease",
			_hover: {
				bg: "whiteAlpha.100",
				color: "whiteAlpha.900",
			},
			_focusVisible: {
				outline: "2px solid",
				outlineColor: "cyan.300",
				outlineOffset: "2px",
			},
			"& svg": {
				width: 4,
				height: 4,
			},
		},
		content: {
			minH: 0,
			overflowY: "auto",
			px: 4,
			py: 3.5,
			scrollbarWidth: "thin",
			scrollbarColor: "rgba(255, 255, 255, 0.22) transparent",
		},
	},
	variants: {
		active: {
			true: {
				railButton: {
					bg: "cyan.400/18",
					borderColor: "cyan.300/46",
					color: "cyan.100",
				},
			},
			false: {},
		},
	},
});
