export const MAP_CANVAS_DEG_TO_RAD = Math.PI / 180;
export const MAP_CANVAS_RAD_TO_DEG = 180 / Math.PI;

export const MAP_CANVAS_GLOBE_RADIUS = 1;
export const MAP_CANVAS_CAMERA_POSITION = [0, 0, 3.25] as const;
export const MAP_CANVAS_CAMERA_FOV = 50;
export const MAP_CANVAS_CAMERA_NEAR = 0.001;
export const MAP_CANVAS_CAMERA_FAR = 100;
export const MAP_CANVAS_MIN_CAMERA_DISTANCE = 1.008;
export const MAP_CANVAS_MAX_CAMERA_DISTANCE = 8;
export const MAP_CANVAS_LINEAR_ZOOM_GAP_STEP = 0.0012;
export const MAP_CANVAS_MIN_ROTATE_SPEED = 0.0015;
export const MAP_CANVAS_MAX_ROTATE_SPEED = 1;
export const MAP_CANVAS_ROTATE_SPEED_GAMMA = 1;

export const MAP_CANVAS_BACKGROUND_COLOR = "#03060a";
export const MAP_CANVAS_GLOBE_COLOR = "#183245";
export const MAP_CANVAS_GRATICULE_COLOR = "#4f667a";
export const MAP_CANVAS_GRATICULE_HOVER_COLOR = "#7dd3fc";
export const MAP_CANVAS_FOOTPRINT_COLOR = "#9fb3c8";
export const MAP_CANVAS_FOOTPRINT_HOVER_COLOR = "#7dd3fc";
export const MAP_CANVAS_FOOTPRINT_SELECTED_COLOR = "#f59e0b";
export const MAP_CANVAS_SOURCE_MARKER_COLOR = "#22d3ee";

export const MAP_CANVAS_GRATICULE_POINT_STEP_DEG = 10;
export const MAP_CANVAS_DEFAULT_GRATICULE_MERIDIAN_STEP_DEG = 30;
export const MAP_CANVAS_DEFAULT_GRATICULE_PARALLEL_STEP_DEG = 30;
export const MAP_CANVAS_GRATICULE_RADIUS_OFFSET = 1.004;
export const MAP_CANVAS_GRATICULE_HOVER_THRESHOLD_PX = 8;
export const MAP_CANVAS_GRATICULE_RA_PRIORITY_EPSILON_PX = 1;

export const MAP_CANVAS_FOOTPRINT_LINE_RADIUS_OFFSET = 1.005;
export const MAP_CANVAS_FOOTPRINT_LINE_WIDTH_PX = 1.25;
export const MAP_CANVAS_FOOTPRINT_HIT_RADIUS_OFFSET =
	MAP_CANVAS_FOOTPRINT_LINE_RADIUS_OFFSET;

export const MAP_CANVAS_SOURCE_MARKER_SIZE_PX = 10;
export const MAP_CANVAS_SOURCE_MARKER_RADIUS_OFFSET =
	MAP_CANVAS_FOOTPRINT_LINE_RADIUS_OFFSET;
export const MAP_CANVAS_SOURCE_MARKER_INACTIVE_OPACITY = 0.95;
export const MAP_CANVAS_SOURCE_MARKER_ACTIVE_CORE_SIZE_SCALE = 1.35;
export const MAP_CANVAS_SOURCE_MARKER_ACTIVE_HALO_SIZE_SCALE = 2.1;
export const MAP_CANVAS_SOURCE_MARKER_ACTIVE_CORE_OPACITY = 1;
export const MAP_CANVAS_SOURCE_MARKER_ACTIVE_HALO_OPACITY = 0.28;
export const MAP_CANVAS_SOURCE_MARKER_ACTIVE_HALO_COLOR = "#ffffff";

export const MAP_CANVAS_COORDINATE_TOOLTIP_OFFSET_PX = 12;
export const MAP_CANVAS_FOOTPRINT_TOOLTIP_MAX_FILES = 2;

export const MAP_CANVAS_GRATICULE_DENSITY_LEVELS = [
	{ maxGap: 0.08, stepDeg: 2 },
	{ maxGap: 0.35, stepDeg: 5 },
	{ maxGap: 1, stepDeg: 10 },
	{ maxGap: 2.5, stepDeg: 15 },
] as const;
