import { defineSlotRecipe } from "@chakra-ui/react";

export const displayTabRecipe = defineSlotRecipe({
	slots: [
		"root",
		"section",
		"sectionTitle",
		"fieldGrid",
		"field",
		"label",
		"rangeDetails",
		"segmentRoot",
		"segmentIndicator",
		"segmentItem",
		"segmentItemText",
		"selectControl",
		"selectContent",
		"selectItem",
		"numberInputRoot",
		"numberInput",
	],
	className: "spectrum-workspace-hud-display-tab",
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			gap: 2.5,
		},
		section: {
			display: "flex",
			flexDirection: "column",
			gap: 2,
		},
		sectionTitle: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.14em",
			textTransform: "uppercase",
			color: "whiteAlpha.560",
		},
		fieldGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 2,
		},
		field: {
			display: "flex",
			flexDirection: "column",
			gap: 1,
		},
		label: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.12em",
			textTransform: "uppercase",
			color: "whiteAlpha.680",
		},
		rangeDetails: {
			display: "flex",
			flexDirection: "column",
			gap: 2,
			minH: "118px",
			pt: 1,
		},
		segmentRoot: {
			display: "inline-flex",
			alignSelf: "flex-start",
			p: 0.75,
			borderRadius: "xl",
			borderWidth: "1px",
			borderColor: "whiteAlpha.180",
			bg: "whiteAlpha.060",
			boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.04)",
		},
		segmentIndicator: {
			borderRadius: "lg",
			bg: "rgba(103, 232, 249, 0.2)",
			borderWidth: "1px",
			borderColor: "rgba(165, 243, 252, 0.28)",
			boxShadow:
				"0 8px 18px rgba(8, 145, 178, 0.16), inset 0 1px 0 rgba(255, 255, 255, 0.16)",
		},
		segmentItem: {
			position: "relative",
			zIndex: 1,
			minW: "92px",
			px: 3,
			py: 1.5,
			borderRadius: "lg",
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			cursor: "pointer",
			color: "whiteAlpha.620",
			transition: "color 0.16s ease, transform 0.16s ease",
			_hover: {
				color: "whiteAlpha.860",
			},
			"&[data-state=checked]": {
				color: "white",
			},
		},
		segmentItemText: {
			fontSize: "xs",
			fontWeight: "semibold",
			letterSpacing: "0.01em",
		},
		selectControl: {
			borderWidth: "1px",
			borderColor: "whiteAlpha.180",
			borderRadius: "lg",
			bg: "whiteAlpha.060",
			color: "white",
			backdropFilter: "blur(12px)",
		},
		selectContent: {
			borderWidth: "1px",
			borderColor: "whiteAlpha.180",
			borderRadius: "lg",
			bg: "rgba(11, 16, 25, 0.96)",
			backdropFilter: "blur(18px)",
			boxShadow: "0 14px 30px rgba(0, 0, 0, 0.34)",
		},
		selectItem: {
			fontSize: "xs",
			borderRadius: "md",
			"&[data-highlighted]": {
				bg: "whiteAlpha.140",
			},
		},
		numberInputRoot: {
			width: "100%",
		},
		numberInput: {
			h: 9,
			borderRadius: "lg",
			borderColor: "whiteAlpha.180",
			bg: "whiteAlpha.050",
			color: "white",
			fontFamily: "mono",
			fontSize: "xs",
			_focusVisible: {
				borderColor: "cyan.300",
				boxShadow: "0 0 0 1px var(--chakra-colors-cyan-300)",
			},
		},
	},
});
