import { defineSlotRecipe } from "@chakra-ui/react";
import { DOCK_WIDTH } from "../../shared/constants";

export const dockRecipe = defineSlotRecipe({
	className: "target-hub-dock",
	slots: [
		"root",
		"shell",
		"sessionCard",
		"sessionDot",
		"status",
		"feedbackLayer",
		"notice",
		"navList",
		"navItem",
		"collapseButton",
	],
	base: {
		root: {
			position: "fixed",
			left: "18px",
			w: `${DOCK_WIDTH}px`,
			zIndex: "var(--target-hub-z-index)",
		},
		shell: {
			p: 3,
			borderRadius: "xl",
			borderWidth: "1px",
			borderColor: "border.subtle",
			bg: "bg.panel",
			backdropFilter: "blur(14px)",
			boxShadow: "0 18px 44px rgba(2, 8, 23, 0.28)",
		},
		sessionCard: {
			p: 3,
			borderRadius: "lg",
			borderWidth: "1px",
			borderColor: "border.subtle",
			bg: "bg.card",
			position: "relative",
			overflow: "hidden",
		},
		sessionDot: {
			w: "10px",
			h: "10px",
			borderRadius: "full",
			flexShrink: 0,
		},
		status: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.12em",
			color: "fg.muted",
		},
		feedbackLayer: {
			position: "absolute",
			inset: "0",
			pointerEvents: "none",
			borderRadius: "inherit",
			overflow: "hidden",
		},
		notice: {
			position: "absolute",
			right: "12px",
			bottom: "10px",
			fontSize: "2xs",
			fontWeight: "medium",
			letterSpacing: "0.08em",
			color: "fg.muted",
			pointerEvents: "none",
		},
		navList: {
			display: "flex",
			flexDirection: "column",
			gap: 1.5,
			mt: 3,
		},
		navItem: {
			justifyContent: "flex-start",
			borderRadius: "lg",
			borderWidth: "1px",
			borderColor: "transparent",
			bg: "transparent",
			color: "fg",
			opacity: 0.88,
			cursor: "default",
			_hover: {
				bg: "bg.card",
				borderColor: "border.subtle",
			},
		},
		collapseButton: {
			mt: 3,
			w: "100%",
			borderRadius: "lg",
		},
	},
});
