import { defineSlotRecipe } from "@chakra-ui/react";

export const imageCanvasRecipe = defineSlotRecipe({
	className: "image-canvas",
	slots: [
		"root",
		"body",
		"mainView",
		"sideRail",
		"roiView",
		"spectrumPreview",
		"sideRailFiller",
	],
	base: {
		root: {
			position: "relative",
			w: "100%",
			h: "100vh",
			minH: 0,
			overflow: "hidden",
			bg: "#050505",
			color: "fg",
			touchAction: "none",
		},
		body: {
			w: "100%",
			h: "100%",
			minH: 0,
			display: "flex",
			alignItems: "stretch",
		},
		mainView: {
			position: "relative",
			flex: "0 0 75%",
			w: "75%",
			minW: 0,
			minH: 0,
			overflow: "hidden",
		},
		sideRail: {
			flex: "0 0 25%",
			w: "25%",
			minH: 0,
			display: "flex",
			flexDirection: "column",
			alignItems: "center",
			gap: 3,
			px: 3,
			pb: 3,
			pt: 0,
			borderLeftWidth: "1px",
			borderColor: "whiteAlpha.200",
			bg: "rgba(8, 12, 16, 0.92)",
		},
		roiView: {
			position: "relative",
			w: "100%",
			h: "auto",
			aspectRatio: "1 / 1",
			overflow: "hidden",
			borderWidth: "1px",
			borderColor: "whiteAlpha.200",
			bg: "#050505",
		},
		spectrumPreview: {
			w: "100%",
			flex: "2 1 0",
			minH: "12rem",
			overflow: "hidden",
			borderWidth: "1px",
			borderColor: "whiteAlpha.200",
			bg: "rgba(0, 0, 0, 0.3)",
		},
		sideRailFiller: {
			w: "100%",
			flex: "1 1 0",
			minH: 0,
		},
	},
});
