export const SPECTRUM_1D_CANVAS_DEFAULT_MARGIN = {
	top: 20,
	right: 30,
	bottom: 50,
	left: 100,
} as const;

export const SPECTRUM_1D_CANVAS_DEFAULT_HEIGHT_RATIO = {
	overview: 0.15,
	slice: 0.8,
	gap: 0.05,
} as const;

export const SPECTRUM_1D_CANVAS_FLUX_PADDING_RATIO = 0.05;
export const SPECTRUM_1D_CANVAS_DEFAULT_FIT_SAMPLE_POINTS = 201;
export const SPECTRUM_1D_CANVAS_MIN_FIT_SAMPLE_POINTS = 2;
export const SPECTRUM_1D_CANVAS_HANDLE_RADIUS_PX = 7;
export const SPECTRUM_1D_CANVAS_HOVER_POINT_RADIUS_PX = 4;
export const SPECTRUM_1D_CANVAS_TOOLTIP_OFFSET_PX = 12;

export const SPECTRUM_1D_CANVAS_ANGSTROM_PER_MICRON = 10000;
export const SPECTRUM_1D_CANVAS_MICRON_PER_ANGSTROM =
	1 / SPECTRUM_1D_CANVAS_ANGSTROM_PER_MICRON;
export const SPECTRUM_1D_CANVAS_SQRT_2_LN2 = Math.sqrt(2 * Math.log(2));
