import { defineSlotRecipe } from "@chakra-ui/react";

export const baseLayerRecipe = defineSlotRecipe({
	className: "image-inspector-base-layer",
	slots: [
		"root",
		"section",
		"sectionHeader",
		"sectionTitle",
		"grismRow",
		"controlGrid",
		"controlRow",
		"label",
		"value",
		"readonlyField",
		"basenameSelectTrigger",
		"selectControl",
		"selectValueText",
		"selectContent",
		"selectItem",
		"segmentRoot",
		"segmentItem",
		"segmentItemText",
		"segmentIndicator",
		"numberRoot",
		"numberInput",
		"switchTrigger",
		"switchControl",
		"fetchButtonTrigger",
		"fetchButton",
		"error",
	],
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			gap: 4.5,
		},
		section: {
			display: "flex",
			flexDirection: "column",
			gap: 2,
		},
		sectionHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 3,
			minH: 8,
		},
		sectionTitle: {
			fontSize: "sm",
			fontWeight: "semibold",
			color: "whiteAlpha.940",
		},
		grismRow: {
			display: "grid",
			gridTemplateColumns: "5.75rem minmax(0, 1fr) 2rem",
			gap: 2,
			alignItems: "end",
		},
		controlGrid: {
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 2,
		},
		controlRow: {
			display: "grid",
			gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
			gap: 2,
			alignItems: "end",
		},
		label: {
			fontSize: "2xs",
			color: "whiteAlpha.560",
			lineHeight: 1.1,
			mb: 1,
		},
		value: {
			fontSize: "xs",
			fontWeight: "medium",
			color: "whiteAlpha.920",
			lineHeight: 1.25,
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		readonlyField: {
			minW: 0,
			h: 8,
			display: "flex",
			alignItems: "center",
			px: 1.5,
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "whiteAlpha.140",
			bg: "blackAlpha.220",
		},
		basenameSelectTrigger: {
			minW: 0,
			display: "block",
		},
		selectControl: {
			"& [data-part=trigger]": {
				minH: 8,
				minW: 0,
				borderRadius: "md",
				borderColor: "whiteAlpha.140",
				bg: "blackAlpha.220",
				color: "whiteAlpha.900",
				fontSize: "xs",
				px: 2,
				_hover: {
					bg: "whiteAlpha.080",
				},
			},
		},
		selectValueText: {
			minW: 0,
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		selectContent: {
			bg: "gray.950",
			borderColor: "whiteAlpha.200",
			color: "whiteAlpha.900",
			zIndex: 1500,
		},
		selectItem: {
			fontSize: "xs",
			_hover: {
				bg: "whiteAlpha.120",
			},
		},
		segmentRoot: {
			minH: 8,
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 1,
			p: 1,
			borderRadius: "md",
			bg: "whiteAlpha.080",
		},
		segmentItem: {
			minW: 0,
			h: 6,
			borderRadius: "sm",
			color: "whiteAlpha.700",
			fontSize: "2xs",
			fontWeight: "medium",
			transition: "color 0.16s ease",
			"&[data-state=checked]": {
				color: "white",
			},
		},
		segmentItemText: {
			position: "relative",
			zIndex: 1,
		},
		segmentIndicator: {
			borderRadius: "sm",
			bg: "whiteAlpha.180",
			boxShadow: "0 8px 18px rgba(0, 0, 0, 0.24)",
		},
		numberRoot: {
			"& [data-part=control]": {
				color: "whiteAlpha.700",
			},
		},
		numberInput: {
			h: 8,
			fontSize: "xs",
			borderColor: "whiteAlpha.140",
			bg: "blackAlpha.220",
			color: "whiteAlpha.900",
		},
		switchTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			p: 1,
			borderRadius: "md",
			borderWidth: "1px",
			borderColor: "whiteAlpha.120",
			bg: "whiteAlpha.060",
			_focusWithin: {
				outline: "2px solid",
				outlineColor: "cyan.300",
				outlineOffset: "2px",
			},
		},
		switchControl: {
			bg: "whiteAlpha.220",
			_checked: {
				bg: "cyan.500",
			},
		},
		fetchButtonTrigger: {
			display: "inline-flex",
			alignItems: "center",
			justifyContent: "center",
			w: 8,
			h: 8,
		},
		fetchButton: {
			w: 8,
			h: 8,
			minW: 8,
			p: 0,
			borderRadius: "md",
			"& svg": {
				w: 4,
				h: 4,
			},
		},
		error: {
			fontSize: "xs",
			color: "red.200",
			lineHeight: 1.35,
		},
	},
});
