import { defineSlotRecipe } from "@chakra-ui/react";

export const hudPanelRecipe = defineSlotRecipe({
	slots: [
		"root",
		"header",
		"titleGroup",
		"eyebrow",
		"title",
		"closeButton",
		"tabsList",
		"tabsTrigger",
		"tabContent",
	],
	className: "spectrum-workspace-hud-panel",
	base: {
		root: {
			position: "relative",
			overflow: "hidden",
			minW: "372px",
			px: 4,
			pt: 4.25,
			pb: 4,
			borderRadius: "2xl",
			borderWidth: "1px",
			borderColor: "whiteAlpha.120",
			bg: "linear-gradient(160deg, rgba(16, 23, 34, 0.74), rgba(6, 10, 17, 0.58))",
			backdropFilter: "blur(26px) saturate(180%)",
			boxShadow:
				"0 20px 48px rgba(0, 0, 0, 0.38), inset 0 1px 0 rgba(255, 255, 255, 0.08)",
			_before: {
				content: '""',
				position: "absolute",
				inset: 0,
				bg: "linear-gradient(180deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.015) 30%, rgba(255, 255, 255, 0) 70%)",
				pointerEvents: "none",
			},
		},
		header: {
			position: "relative",
			zIndex: 1,
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			gap: 3,
			mb: 3,
			px: 0.5,
		},
		titleGroup: {
			display: "flex",
			flexDirection: "column",
			gap: 0,
			pl: 0.5,
		},
		eyebrow: {
			fontSize: "2xs",
			fontWeight: "bold",
			letterSpacing: "0.16em",
			textTransform: "uppercase",
			color: "whiteAlpha.700",
		},
		title: {
			fontSize: "sm",
			fontWeight: "semibold",
			color: "white",
		},
		closeButton: {
			w: 9,
			h: 9,
			borderRadius: "full",
			borderWidth: "1px",
			borderColor: "whiteAlpha.180",
			bg: "whiteAlpha.100",
			color: "whiteAlpha.900",
			transition:
				"transform 0.18s ease, background 0.18s ease, box-shadow 0.18s ease",
			_hover: {
				transform: "translateY(-1px)",
				bg: "whiteAlpha.160",
				boxShadow: "0 8px 18px rgba(0, 0, 0, 0.24)",
			},
			_focusVisible: {
				outline: "2px solid",
				outlineColor: "cyan.300",
				outlineOffset: "2px",
			},
		},
		tabsList: {
			position: "relative",
			zIndex: 1,
			display: "grid",
			gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
			gap: 1,
			mb: 2.5,
			p: 1,
			borderRadius: "xl",
			bg: "whiteAlpha.080",
		},
		tabsTrigger: {
			borderRadius: "lg",
			px: 3,
			py: 1.5,
			fontSize: "xs",
			fontWeight: "medium",
			color: "whiteAlpha.700",
			transition: "background 0.18s ease, color 0.18s ease",
			_hover: {
				color: "whiteAlpha.900",
			},
			"&[data-state=active]": {
				bg: "whiteAlpha.180",
				color: "white",
				boxShadow: "0 10px 22px rgba(0, 0, 0, 0.2)",
			},
		},
		tabContent: {
			position: "relative",
			zIndex: 1,
			px: 0.75,
		},
	},
});
