/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WfssRouteImport } from './routes/wfss'
import { Route as SedRouteImport } from './routes/sed'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'

const WfssRoute = WfssRouteImport.update({
  id: '/wfss',
  path: '/wfss',
  getParentRoute: () => rootRouteImport,
} as any)
const SedRoute = SedRouteImport.update({
  id: '/sed',
  path: '/sed',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/sed': typeof SedRoute
  '/wfss': typeof WfssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/sed': typeof SedRoute
  '/wfss': typeof WfssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/sed': typeof SedRoute
  '/wfss': typeof WfssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog' | '/sed' | '/wfss'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/sed' | '/wfss'
  id: '__root__' | '/' | '/catalog' | '/sed' | '/wfss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  SedRoute: typeof SedRoute
  WfssRoute: typeof WfssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wfss': {
      id: '/wfss'
      path: '/wfss'
      fullPath: '/wfss'
      preLoaderRoute: typeof WfssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sed': {
      id: '/sed'
      path: '/sed'
      fullPath: '/sed'
      preLoaderRoute: typeof SedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  SedRoute: SedRoute,
  WfssRoute: WfssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
